### ISSUE TITLE
Running `jamie list` with no config ends in failure

### ISSUE THREAD

**Issue by miketheman** [jamie-ci/jamie#11]
On fresh system:

``` bash
$ jamie list
       Terminating 4 actors...
       Shutdown completed cleanly
/Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:254:in `read': No such file or directory - /Users/michael/tmp/jamie/.jamie.yml (Errno::ENOENT)
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:254:in `yaml_contents'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:250:in `yaml'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:107:in `suites'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:176:in `load_instances'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:113:in `instances'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie/cli.rb:176:in `get_filtered_instances'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie/cli.rb:163:in `parse_subcommand'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie/cli.rb:44:in `list'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/bin/jamie:12:in `<top (required)>'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/jamie:19:in `load'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/jamie:19:in `<main>'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/ruby_noexec_wrapper:14:in `<main>'
```

Should probably capture this and message user.

**Comment by fnichol** [comment]
Similar to #12 we'll want to raise a `Jamie::UserError` if there are any issues loading and processing the YAML files. That should allow the CLI to show a prettier error message before dying.

**Comment by sethvargo** [comment]
We should hide the stack trace by default. Specifying the --debug or --verbose option can display the full trace. Thoughts?

**Comment by miketheman** [comment]
Closing. `kitchen list` handles this much cleaner now.
