### ISSUE TITLE
Running `jamie init` with no cookbook metadata.rb ends in failure

### ISSUE THREAD

**Issue by miketheman** [jamie-ci/jamie#12]
On empty directory:

``` bash
$ jamie init
       Terminating 4 actors...
       Shutdown completed cleanly
/Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:1532:in `read': No such file or directory - /Users/michael/tmp/jamie/metadata.rb (Errno::ENOENT)
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:1532:in `initialize'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:1522:in `new'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie.rb:1522:in `extract'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie/cli.rb:269:in `default_yaml'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie/cli.rb:225:in `init'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/lib/jamie/cli.rb:123:in `init'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/gems/jamie-0.1.0.beta1/bin/jamie:12:in `<top (required)>'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/jamie:19:in `load'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/jamie:19:in `<main>'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/michael/.rvm/gems/ruby-1.9.3-p327@tmp/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by fnichol** [comment]
Yep, we'll want a graceful failure (non-zero exit) here, most likely by raising a `Jamie::UserError` if:
- no metadata.rb file exists or
- the `name` attribute isn't set

**Comment by miketheman** [comment]
This no longer ends in failure - does `init` no longer look for `metadata.rb`?

**Comment by fnichol** [comment]
Right, this was handled by bdba82b. Still might flame out if `name` attribute isn't set.

**Comment by miketheman** [comment]
Gotcha.

Both are use cases I can add to the `cli_init.feature` in short order.

**Comment by miketheman** [comment]
In the event that MetadataChopper cannot extract a name, the rendered yaml file shows:

``` yaml
suites:
- name: default
  run_list: []
  attributes: {}
```

If Jamie cannot determine the name properly, then I would guess raising an error might be in order.

**Comment by miketheman** [comment]
I suspect my latest commit will close this issue.
